# Generated by Django 5.0.4 on 2024-06-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(max_length=20, unique=True)),
                ('network_type', models.CharField(choices=[('voda', 'Vodacom'), ('airtel', 'Airtel'), ('tigo', 'Tigo'), ('zantel', 'Zantel'), ('ttcl', 'TTCL'), ('halotel', 'Halotel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_timestamp', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.networkcredit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
