# Generated by Django 5.0.4 on 2024-06-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcredit',
            name='user',
        ),
    ]
