# Generated by Django 5.0.4 on 2024-06-19 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_otpcredit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcredit',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkcredit',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpcredit',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_credits', to='sms.networkcredit'),
        ),
        migrations.AlterField(
            model_name='otpcredit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
