# Generated by Django 5.0.4 on 2024-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_networkcredit_sent_timestamp_networkcredit_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitedPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('benefited_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
