# Generated by Django 5.0.4 on 2024-06-19 15:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_benefitedphonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcredit',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 15, 6, 36, 112575, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpcredit',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.networkcredit'),
        ),
        migrations.AlterField(
            model_name='otpcredit',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
