# Generated by Django 5.0.4 on 2024-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_otpcredit_otp_expiry_alter_otpcredit_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcredit',
            name='otp_expiry',
            field=models.DateTimeField(),
        ),
    ]
