# Generated by Django 4.2.13 on 2024-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_alter_otpcredit_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcredit',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
