# Generated by Django 5.0.7 on 2025-06-08 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-Time')], default='monthly', max_length=20)),
                ('plan_tier', models.CharField(choices=[('anza', 'Anza (Starter)'), ('endeleza', 'Endeleza (Grow)'), ('dumu', 'Dumu (Enterprise)'), ('custom', 'Custom One-Time')], default='anza', max_length=20)),
                ('business_count', models.PositiveIntegerField(default=1, help_text='Number of businesses allowed')),
                ('has_offline_mode', models.BooleanField(default=False)),
                ('has_multi_device', models.BooleanField(default=False)),
                ('device_access', models.CharField(default='Mobile (Android & iOS Only)', max_length=100)),
                ('has_advanced_inventory', models.BooleanField(default=False)),
                ('has_supplier_integration', models.BooleanField(default=False)),
                ('has_full_financial', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_multi_store', models.BooleanField(default=False)),
                ('sms_tier', models.CharField(default='Limited', help_text='SMS tier: Limited, Standard, or Advanced', max_length=20)),
                ('support_tier', models.CharField(default='Email Support', max_length=50)),
                ('featured', models.BooleanField(default=False, help_text='Whether to highlight this plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('trial_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paywall.paymentplan')),
            ],
        ),
    ]
