# Generated by Django 5.0.7 on 2025-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='business_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of businesses allowed'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='device_access',
            field=models.CharField(default='Mobile (Android & iOS Only)', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether to highlight this plan'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_advanced_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_full_financial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_multi_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_multi_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_offline_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='has_supplier_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='plan_tier',
            field=models.CharField(choices=[('anza', 'Anza (Starter)'), ('endeleza', 'Endeleza (Grow)'), ('dumu', 'Dumu (Enterprise)'), ('custom', 'Custom One-Time')], default='anza', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One-Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='sms_tier',
            field=models.CharField(default='Limited', help_text='SMS tier: Limited, Standard, or Advanced', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='support_tier',
            field=models.CharField(default='Email Support', max_length=50),
        ),
    ]
