# Generated by Django 4.1.7 on 2024-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Barcode',
            field=models.CharField(max_length=255),
        ),
    ]
