# Generated by Django 4.2 on 2024-05-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, choices=[('mls', 'mls'), ('kg', 'kg'), ('g', 'g')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='unity_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
