# Generated by Django 4.1.7 on 2024-04-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_warehouse_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='inventory.product')),
            ],
        ),
    ]
