# Generated by Django 5.0.7 on 2024-10-11 16:31

import django.utils.crypto
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('unit', models.CharField(blank=True, choices=[('mls', 'Milliliters'), ('l', 'Liters'), ('g', 'Grams'), ('kg', 'Kilograms'), ('doz', 'Dozens'), ('pcs', 'Pieces'), ('box', 'Boxes')], max_length=3, null=True)),
                ('unit_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('isSynced', models.BooleanField(default=False)),
                ('lastSyncTime', models.DateTimeField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_number', models.CharField(default=django.utils.crypto.get_random_string, max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('before_tax_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_tax_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_status', models.BooleanField(default=False)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Loan', 'Loan')], default='Cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Supplies', 'Supplies'), ('Meals', 'Meals'), ('Other', 'Other')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_description', models.TextField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Supplies', 'Supplies'), ('Meals', 'Meals'), ('Other', 'Other')], default=0, max_length=50, null=True)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enforcement_day', models.IntegerField()),
                ('impacted_roles', models.CharField(choices=[('management', 'Management'), ('sales', 'Sales'), ('general', 'General Team')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_interval', models.CharField(choices=[('3_days', '3 Days'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month')], default='3_days', max_length=10)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('discountable', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isSynced', models.BooleanField(default=False)),
                ('lastSyncTime', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('min_stock', models.IntegerField(blank=True, default=20, help_text='Minimum stock level to trigger restock warning', null=True)),
                ('max_stock', models.IntegerField(blank=True, help_text='Maximum stock level to prevent overstocking', null=True)),
                ('location_type', models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('Shop', 'Shop'), ('online', 'online')], default='store', max_length=50, null=True)),
                ('location_identifier', models.CharField(blank=True, help_text='Specific shelf or aisle in the store', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductBusinessTypeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(default='default_barcode_value', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('cash', 'Cash'), ('lipa_namba', 'Lipa Kwa Simu'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_synced', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('supplierName', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactPhone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('supplierType', models.CharField(choices=[('Manufacturer', 'Manufacturer'), ('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('Retailer', 'Retailer'), ('Other', 'Other')], default='Other', max_length=50)),
                ('isSynced', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(max_length=255)),
                ('warehouseLocation', models.CharField(max_length=255)),
            ],
        ),
    ]
