# Generated by Django 5.0.7 on 2024-08-27 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.expensecategory'),
        ),
        migrations.AddField(
            model_name='installment',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='installment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registration.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='publicproduct',
            unique_together={('product_name', 'barcode')},
        ),
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.customer'),
        ),
        migrations.AddField(
            model_name='installment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='sales',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='sales',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='installment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='draftorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.address'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.transaction')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('purchase_order_number', models.CharField(default=1, max_length=20, unique=True)),
                ('lpo_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
