# Generated by Django 5.0.7 on 2024-08-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='isSynced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='lastSyncTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
