# Generated by Django 5.0.7 on 2025-06-08 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=20, unique=True)),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_type', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('supplier', 'Supplier')], max_length=50)),
                ('loan_type', models.CharField(choices=[('product_purchase', 'Product Purchase'), ('salary_advance', 'Salary Advance'), ('inventory_credit', 'Inventory Credit'), ('equipment_purchase', 'Equipment Purchase'), ('catering_services', 'Catering Services'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.business')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
