# Generated by Django 5.0.7 on 2024-10-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='isSynced',
            field=models.BooleanField(default=False),
        ),
    ]
