# Generated by Django 4.2.14 on 2024-09-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_type',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('Shop', 'Shop'), ('online', 'online')], default='store', max_length=50, null=True),
        ),
    ]
