# Generated by Django 4.2 on 2024-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehouse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ExpireDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discountable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
