# Generated by Django 5.0.7 on 2024-10-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_sales_product_remove_sales_quantity_salesitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
