# Generated by Django 5.0.7 on 2024-10-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_transaction_installment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction'),
        ),
    ]
