# Generated by Django 4.2.14 on 2024-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSynced',
            field=models.BooleanField(default=False),
        ),
    ]
