# Generated by Django 4.2.13 on 2024-06-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_business_qr_image'),
        ('inventory', '0007_category_unit_category_unity_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_updated']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='unity_quantity',
            new_name='unit_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DateUpdated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ExpireDate',
            new_name='expire_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Supplier',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Warehouse',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='WarehouseLocation',
            new_name='warehouse_location',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='WarehouseName',
            new_name='warehouse_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.business'),
        ),
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, choices=[('mls', 'Milliliters'), ('l', 'Liters'), ('g', 'Grams'), ('kg', 'Kilograms'), ('doz', 'Dozens'), ('pcs', 'Pieces'), ('box', 'Boxes')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('lipa_namba', 'Lipa Kwa Simu'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
