# Generated by Django 4.2.14 on 2024-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_issynced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lastSyncTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
