# Generated by Django 4.2.14 on 2024-09-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_lastsynctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='is_deleted',
            new_name='isDeleted',
        ),
    ]
