# Generated by Django 4.2.14 on 2024-09-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_is_deleted_product_isdeleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoryName',
        ),
    ]
