# Generated by Django 5.0.7 on 2024-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_sales_id_alter_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='business',
            new_name='business_id',
        ),
    ]
