# Generated by Django 4.2.14 on 2024-09-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_category_name_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
    ]
