# Generated by Django 4.2.14 on 2024-09-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='transaction',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
