# Generated by Django 5.0.7 on 2024-10-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_business_sales_business_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='business',
            new_name='business_id',
        ),
    ]
