# Generated by Django 4.2.14 on 2024-09-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_transaction_sales_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.transaction'),
        ),
    ]
