# Generated by Django 5.0.7 on 2024-10-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_business_transaction_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction'),
        ),
    ]
