# Generated by Django 5.0.7 on 2024-10-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_sales_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='business_id',
            new_name='business',
        ),
    ]
