# Generated by Django 4.2.14 on 2024-09-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_sales_product_alter_sales_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
