# Generated by Django 5.0.7 on 2024-10-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_business_id_sales_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='business_id',
            new_name='business',
        ),
    ]
