# Generated by Django 4.2.14 on 2024-09-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_transaction_id_sales_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
