# Generated by Django 5.0.7 on 2024-10-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_business_id_transaction_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='after_tax_cost',
            new_name='with_tax_cost',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='before_tax_cost',
            new_name='without_tax_cost',
        ),
    ]
