# Generated by Django 4.2.14 on 2024-09-30 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0004_address_profile_businessprofile'),
        ('inventory', '0015_rename_supplier_product_supplier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_description', models.TextField()),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Supplies', 'Supplies'), ('Meals', 'Meals'), ('Other', 'Other')], default=0, max_length=50, null=True)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enforcement_day', models.IntegerField()),
                ('impacted_roles', models.CharField(choices=[('management', 'Management'), ('sales', 'Sales'), ('general', 'General Team')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Supplies', 'Supplies'), ('Meals', 'Meals'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
