# Generated by Django 5.0.7 on 2024-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_expensecategory_alter_expense_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
