# Generated by Django 4.2.14 on 2024-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tinNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
