# Generated by Django 5.0.4 on 2024-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('storekeeper', 'Storekeeper'), ('inventory_manager', 'Inventory Manager')], default='admin', max_length=100),
        ),
    ]
