# Generated by Django 4.2.14 on 2024-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_address_profile_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
    ]
