# Generated by Django 5.0.4 on 2024-06-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='address',
            new_name='business_address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='phone_number',
            new_name='business_phone_number',
        ),
    ]
