# Generated by Django 5.0.4 on 2024-06-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_rename_address_business_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
