# Generated by Django 5.0.4 on 2024-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='has_benefited_from_offer',
            field=models.BooleanField(default=False),
        ),
    ]
