# Generated by Django 4.2.13 on 2024-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_business_has_benefited_from_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
