# Generated by Django 4.2.13 on 2024-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vcard_qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='vcards/'),
        ),
    ]
