# Generated by Django 4.2.13 on 2024-07-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_business_website_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
