# Generated by Django 4.2 on 2024-04-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_warehouse_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This field can contain any text, URL, etc.', verbose_name='Data to encode')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='inventory.product')),
            ],
        ),
    ]
