# Generated by Django 5.0.7 on 2024-08-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='This field can contain any text, URL, etc.', verbose_name='Data to encode')),
                ('qrImage', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrImage', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='inventory.product')),
            ],
        ),
    ]
