# Generated by Django 4.2 on 2024-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
